namespace Dynamics365ImportData.Comparison;

using System.Text;

using Dynamics365ImportData.Comparison.Models;
using Dynamics365ImportData.Persistence.Models;
using Dynamics365ImportData.Settings;

using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

public class ErrorComparisonReportService : IErrorComparisonReportService
{
    private readonly IOptions<DestinationSettings> _destinationSettings;
    private readonly ILogger<ErrorComparisonReportService> _logger;

    public ErrorComparisonReportService(
        IOptions<DestinationSettings> destinationSettings,
        ILogger<ErrorComparisonReportService> logger)
    {
        _destinationSettings = destinationSettings;
        _logger = logger;
    }

    public async Task<string> GenerateReportAsync(
        ComparisonResult comparison,
        string? outputPath = null,
        CancellationToken cancellationToken = default)
    {
        var markdown = BuildMarkdown(comparison);
        var filePath = outputPath ?? GetDefaultOutputPath(comparison);

        var directory = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);

        await File.WriteAllTextAsync(filePath, markdown, cancellationToken);
        _logger.LogInformation("Error comparison report written to {ReportPath}", filePath);
        return filePath;
    }

    private string GetDefaultOutputPath(ComparisonResult comparison)
    {
        var outputDir = _destinationSettings.Value.OutputDirectory ?? ".";
        var cycleId = comparison.CurrentCycleId;
        return Path.Combine(outputDir, $"error-comparison-{cycleId}.md");
    }

    private static string BuildMarkdown(ComparisonResult comparison)
    {
        if (comparison.IsFirstCycle)
            return BuildFirstCycleMarkdown(comparison);

        return BuildComparisonMarkdown(comparison);
    }

    private static string BuildFirstCycleMarkdown(ComparisonResult comparison)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Error Comparison Report");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {comparison.Timestamp:O}");
        sb.AppendLine($"**Current Cycle:** {comparison.CurrentCycleId}");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("First cycle -- no comparison available. Run another migration cycle to enable error comparison.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*Generated by d365fo-data-migration*");
        return sb.ToString();
    }

    private static string BuildComparisonMarkdown(ComparisonResult comparison)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("# Error Comparison Report");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {comparison.Timestamp:O}");
        sb.AppendLine($"**Current Cycle:** {comparison.CurrentCycleId}");
        sb.AppendLine($"**Previous Cycle:** {comparison.PreviousCycleId}");
        sb.AppendLine();

        // Summary table
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Count |");
        sb.AppendLine("|--------|-------|");
        sb.AppendLine($"| New Errors | {comparison.TotalNewErrors} |");
        sb.AppendLine($"| Carry-Over Errors | {comparison.TotalCarryOverErrors} |");
        sb.AppendLine($"| Resolved Errors | {comparison.TotalResolvedErrors} |");
        sb.AppendLine($"| Total Current Errors | {comparison.TotalNewErrors + comparison.TotalCarryOverErrors} |");
        sb.AppendLine();

        // Entity details
        sb.AppendLine("## Entity Details");
        sb.AppendLine();

        foreach (var entity in comparison.EntityComparisons)
        {
            var statusLabel = FormatStatus(entity.CurrentStatus);
            sb.AppendLine($"### `{entity.EntityName}` - {statusLabel}");
            sb.AppendLine();
            sb.AppendLine("| Type | Count |");
            sb.AppendLine("|------|-------|");
            sb.AppendLine($"| New | {entity.NewErrors.Count} |");
            sb.AppendLine($"| Carry-Over | {entity.CarryOverErrors.Count} |");
            sb.AppendLine($"| Resolved | {entity.ResolvedFingerprints.Count} |");
            sb.AppendLine();

            if (entity.NewErrors.Count > 0)
            {
                sb.AppendLine("**New Errors:**");
                foreach (var error in entity.NewErrors)
                {
                    sb.AppendLine($"- `[{error.Fingerprint}]` {error.Message}");
                }
                sb.AppendLine();
            }

            if (entity.CarryOverErrors.Count > 0)
            {
                sb.AppendLine("**Carry-Over Errors:**");
                foreach (var error in entity.CarryOverErrors)
                {
                    sb.AppendLine($"- `[{error.Fingerprint}]` {error.Message}");
                }
                sb.AppendLine();
            }

            if (entity.ResolvedFingerprints.Count > 0)
            {
                sb.AppendLine("**Resolved (from previous cycle):**");
                foreach (var fingerprint in entity.ResolvedFingerprints)
                {
                    sb.AppendLine($"- `[{fingerprint}]`");
                }
                sb.AppendLine();
            }
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine("*Generated by d365fo-data-migration*");
        return sb.ToString();
    }

    private static string FormatStatus(EntityStatus status) => status switch
    {
        EntityStatus.Failed => "FAIL",
        EntityStatus.Success => "pass",
        EntityStatus.Warning => "warn",
        EntityStatus.Skipped => "skip",
        _ => status.ToString().ToLowerInvariant()
    };
}
