namespace Dynamics365ImportData.Tests.Integration.Reporting;

using Dynamics365ImportData.Persistence;
using Dynamics365ImportData.Persistence.Models;
using Dynamics365ImportData.Pipeline;
using Dynamics365ImportData.Reporting;
using Dynamics365ImportData.Settings;

using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

using NSubstitute;

using Shouldly;

using Xunit;

public class ReadinessReportIntegrationTests : IDisposable
{
    private readonly string _tempDir;

    public ReadinessReportIntegrationTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"ReadinessIntegration_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_tempDir, true); }
        catch { /* cleanup best-effort */ }
    }

    [Fact]
    public async Task GenerateAsync_WithRealFileIO_WritesMarkdownFile()
    {
        // Arrange
        var repository = Substitute.For<IMigrationResultRepository>();
        var cycles = new List<CycleResult>
        {
            CreateCycle("cycle-2026-01-30T100000",
                new DateTimeOffset(2026, 1, 30, 10, 0, 0, TimeSpan.Zero),
                CreateEntityResult("CustCustomerV3Entity", 3),
                CreateEntityResult("smmContactPersonV2Entity", 0))
        };
        repository.GetLatestCycleResultsAsync(Arg.Any<int>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult<IReadOnlyList<CycleResult>>(cycles));

        var reportSettings = Options.Create(new ReportSettings
        {
            DefaultCycleRange = 5,
            SuccessThreshold = 0,
            WarningThreshold = 5,
            OutputDirectory = _tempDir
        });
        var destinationSettings = Options.Create(new DestinationSettings { OutputDirectory = _tempDir });
        var service = new ReadinessReportService(
            repository, reportSettings, destinationSettings,
            NullLogger<ReadinessReportService>.Instance);

        // Act
        var filePath = await service.GenerateAsync();

        // Assert
        filePath.ShouldNotBeNull();
        File.Exists(filePath).ShouldBeTrue();
        var fileInfo = new FileInfo(filePath);
        fileInfo.Length.ShouldBeGreaterThan(0);
        fileInfo.Extension.ShouldBe(".md");
    }

    [Fact]
    public async Task GenerateAsync_EndToEnd_ProducesValidMarkdown()
    {
        // Arrange
        var repository = Substitute.For<IMigrationResultRepository>();
        var cycles = new List<CycleResult>
        {
            CreateCycle("cycle-2026-01-28T100000",
                new DateTimeOffset(2026, 1, 28, 10, 0, 0, TimeSpan.Zero),
                CreateEntityResult("CustCustomerV3Entity", 5),
                CreateEntityResult("smmContactPersonV2Entity", 10)),
            CreateCycle("cycle-2026-01-29T100000",
                new DateTimeOffset(2026, 1, 29, 10, 0, 0, TimeSpan.Zero),
                CreateEntityResult("CustCustomerV3Entity", 3),
                CreateEntityResult("smmContactPersonV2Entity", 0))
        };
        // Repository returns latest-first
        var orderedCycles = cycles.OrderByDescending(c => c.Timestamp).ToList();
        repository.GetLatestCycleResultsAsync(Arg.Any<int>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult<IReadOnlyList<CycleResult>>(orderedCycles));

        var reportSettings = Options.Create(new ReportSettings
        {
            DefaultCycleRange = 5,
            SuccessThreshold = 0,
            WarningThreshold = 5,
            OutputDirectory = _tempDir
        });
        var destinationSettings = Options.Create(new DestinationSettings { OutputDirectory = _tempDir });
        var service = new ReadinessReportService(
            repository, reportSettings, destinationSettings,
            NullLogger<ReadinessReportService>.Instance);

        // Act
        var filePath = await service.GenerateAsync();

        // Assert
        filePath.ShouldNotBeNull();
        var content = await File.ReadAllTextAsync(filePath);

        // Verify complete markdown structure
        content.ShouldContain("# Migration Readiness Report");
        content.ShouldContain("**Generated:**");
        content.ShouldContain("**Cycles Analyzed:** 2 of 5");
        content.ShouldContain("## Summary");
        content.ShouldContain("## Error Trends");
        content.ShouldContain("## Entity Details");
        content.ShouldContain("### `CustCustomerV3Entity`");
        content.ShouldContain("### `smmContactPersonV2Entity`");
        content.ShouldContain("---");
        content.ShouldContain("*Generated by d365fo-data-migration*");

        // Verify entity classifications (latest cycle: CustCustomer=3 -> warn, smm=0 -> pass)
        content.ShouldContain("### `CustCustomerV3Entity` - warn");
        content.ShouldContain("### `smmContactPersonV2Entity` - pass");

        // Verify trend data is present
        content.ShouldContain("cycle-2026-01-28T100000");
        content.ShouldContain("cycle-2026-01-29T100000");

        // Verify fewer cycles note (2 of 5 requested)
        content.ShouldContain("> **Note:** Only 2 cycle(s) available of 5 requested.");
    }

    private static CycleResult CreateCycle(
        string cycleId,
        DateTimeOffset timestamp,
        params EntityResult[] results)
    {
        return new CycleResult
        {
            CycleId = cycleId,
            Timestamp = timestamp,
            Results = results.ToList(),
            TotalEntities = results.Length,
            Succeeded = results.Count(r => r.Errors.Count == 0),
            Failed = results.Count(r => r.Errors.Count > 0)
        };
    }

    private static EntityResult CreateEntityResult(string entityName, int errorCount)
    {
        return new EntityResult
        {
            EntityName = entityName,
            Status = errorCount == 0 ? EntityStatus.Success : EntityStatus.Failed,
            Errors = Enumerable.Range(0, errorCount)
                .Select(i => new EntityError
                {
                    Message = $"Error {i} for {entityName}",
                    Fingerprint = $"{entityName.GetHashCode():X8}{i:D8}"
                }).ToList()
        };
    }
}
